name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ~1.x
      - name: Test Deno
        run: deno test
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm i
      - name: Version
        run: npx changeset version
      - name: Read Version
        id: version
        run: echo ::set-output name=VERSION::$(cat package.json | jq '.version')
      - name: Needs Publishing
        run: echo ::set-output name=CHANGES::$(git status -s .changeset CHANGELOG.md package.json | wc -l)
        id: needs_publishing
      - name: Remove Dependencies
        run: rm -rf node_modules
      - name: Build and Test Node.js
        run: deno task build
      - name: Publish ${{ steps.version.outputs.VERSION }}
        if: steps.needs_publishing.outputs.CHANGES != '0'
        uses: JS-DevTools/npm-publish@v2
        with:
          package: "npm"
          token: ${{ secrets.NPM_TOKEN }}
      - name: Push Changes ${{ steps.version.outputs.VERSION }}
        if: steps.needs_publishing.outputs.CHANGES != '0'
        uses: EndBug/add-and-commit@v9
        with:
          add: '[".changeset", "CHANGELOG.md", "package.json"]'
          push: true
          tag: ${{ steps.version.outputs.VERSION }}
